site_name: WackyTracky Documentation
docs_dir: source
repo_url: https://github.com/wacky-tracky/WackyTracky/
nav:
  - Home: index.md
  - Installation:
    - Docker Compose: installation/docker-compose.md
  - Backends:
    - Overview: backends/index.md
    - todo.txt: backends/todotxt.md
    - Neo4j: backends/neo4j.md
    - YAML files: backends/yamlfiles.md
  - API:
    - Overview: api/index.md
    - Reference: api/reference.md
    - Search: api/search.md
theme:
  name: material
  logo: assets/logo.svg
  palette:
    primary: teal
